<?php

/**
 * BaseProject
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $description
 * @property Doctrine_Collection $ProjectTag
 * 
 * @method string              getTitle()       Returns the current record's "title" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method Doctrine_Collection getProjectTag()  Returns the current record's "ProjectTag" collection
 * @method Project             setTitle()       Sets the current record's "title" value
 * @method Project             setDescription() Sets the current record's "description" value
 * @method Project             setProjectTag()  Sets the current record's "ProjectTag" collection
 * 
 * @package    fortfolio
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProject extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('project');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ProjectTag', array(
             'local' => 'id',
             'foreign' => 'project_id'));
    }
}