<?php

/**
 * BaseProjectTag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $project_id
 * @property integer $tag_id
 * @property Project $Project
 * @property Tag $Tag
 * 
 * @method integer    getProjectId()  Returns the current record's "project_id" value
 * @method integer    getTagId()      Returns the current record's "tag_id" value
 * @method Project    getProject()    Returns the current record's "Project" value
 * @method Tag        getTag()        Returns the current record's "Tag" value
 * @method ProjectTag setProjectId()  Sets the current record's "project_id" value
 * @method ProjectTag setTagId()      Sets the current record's "tag_id" value
 * @method ProjectTag setProject()    Sets the current record's "Project" value
 * @method ProjectTag setTag()        Sets the current record's "Tag" value
 * 
 * @package    fortfolio
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProjectTag extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('project_tag');
        $this->hasColumn('project_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('tag_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Project', array(
             'local' => 'project_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Tag', array(
             'local' => 'tag_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}