<?php

/**
 * BaseTag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $ProjectTag
 * 
 * @method string              getName()       Returns the current record's "name" value
 * @method Doctrine_Collection getProjectTag() Returns the current record's "ProjectTag" collection
 * @method Tag                 setName()       Sets the current record's "name" value
 * @method Tag                 setProjectTag() Sets the current record's "ProjectTag" collection
 * 
 * @package    fortfolio
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTag extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tag');
        $this->hasColumn('name', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ProjectTag', array(
             'local' => 'id',
             'foreign' => 'tag_id'));
    }
}